### ISSUE TITLE
Mailer configuration not loaded when using alternate transport class

### ISSUE THREAD

**Issue by alrayyes** [LExpress/symfony1#104]
Hi,

When I config the following in factories.yml:

```yaml
mailer:
      param:
        delivery_strategy:  single_address
        delivery_address: example@example.com
        transport:
          class: Swift_SmtpTransport
          param:
            host: smtp.example.com
            port: 25
            encryption: ~
            username: user
            password: password
```

The config options aren't loaded. Here's a var_dump of the $parameters in sfFactoryConfigHandler:

```php
array(4) {
  ["logging"]=>
  string(0) ""
  ["charset"]=>
  string(5) "utf-8"
  ["delivery_strategy"]=>
  string(8) "realtime"
  ["transport"]=>
  array(2) {
    ["class"]=>
    string(19) "Swift_SmtpTransport"
    ["param"]=>
    array(5) {
      ["host"]=>
      string(9) "localhost"
      ["port"]=>
      int(25)
      ["encryption"]=>
      NULL
      ["username"]=>
      NULL
      ["password"]=>
      NULL
    }
  }
}
```

Is this a bug or am I doing something wrong?

**Comment by alrayyes** [comment]
It works if I set the $parameters manually in sfFactoryConfigHandler::Execute() unser case 'mailer':. I'm guessing something is broken in the config reader.

**Comment by j0k3r** [comment]
What's your full `factories.yml`? Don't you have a wrong tabulation spaces somewhere?

**Comment by alrayyes** [comment]
Not than I can see:

```yaml
# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/05-Factories

prod:
  logger:
    class:   sfNoLogger
    param:
      level:   err
      loggers: ~
    mailer:
      param:
        delivery_strategy:  single_address
        delivery_address: example@example.com
        transport:
          class: Swift_SmtpTransport
          param:
            host: smtp.example.com
            port: 25
            encryption: ~
            username: smtp@example.com
            password: password


test:
  storage:
    class: sfSessionTestStorage
    param:
      session_path: %SF_TEST_CACHE_DIR%/sessions

  response:
    class: sfWebResponse
    param:
      send_http_headers: false

  mailer:
    param:
      delivery_strategy: none

dev:
  mailer:
    param:
      delivery_strategy: none
      transport:
        class: Swift_NullTransport

staging:
  mailer:
    param:
      delivery_strategy:  single_address
      delivery_address: example@example.com

#prod:
#  mailer:
#    param:
#      delivery_strategy:  single_address
#      delivery_address: example@example.com
            
all:
  routing:
    class: sfPatternRouting
    param:
      generate_shortest_url:            true
      extra_parameters_as_query_string: true

  view_cache_manager:
    class: sfViewCacheManager
    param:
      cache_key_use_vary_headers: true
      cache_key_use_host_name:    true

  user:
    class: myUser
    param:
      timeout:  3600
```

**Comment by j0k3r** [comment]
Your `mailer` is *inside* the logger configuration.

You should have:

```yaml
prod:
  logger:
    class:   sfNoLogger
    param:
      level:   err
      loggers: ~

  mailer:
    param:
      delivery_strategy:  single_address
      delivery_address: example@example.com
      transport:
        class: Swift_SmtpTransport
        param:
          host: smtp.example.com
          port: 25
          encryption: ~
          username: smtp@example.com
          password: password
```
