### ISSUE TITLE
Dynamic YAML file issue

### ISSUE THREAD

**Issue by ncharlot** [LExpress/symfony1#119]
Hello,

Just started to update a big Sf 1.4 app.
Stay blocked on an issue with a routing.yml containing PHP:

```yaml
ranking_championship_scorers_fr:
  url:     /saison-:period_slug/:championship/equipe-:team/classement-buteurs-championnat.html
  class:   myRoute
  param:   { module: componentRanking, action: index, ranking_type: "<?php echo RankingForm::VIEW_SCORERS ?>", type: "<?php echo PlayerStatsPeer::TYPE_CHAMPIONSHIP ?>" }
  requirements:
    active_component: team
```

And the error:
```
Unable to parse file "/Volumes/Code/myapp/apps/frontend/config/routing.yml": Malformed inline YAML string ({ module: componentRanking, action: index, ranking_type: 1..109).
```

Any idea?
