### ISSUE TITLE
[sfDoctrinePlugin] When merge schema files global parameters are not deep merged like Doctrine1 done

### ISSUE THREAD

**Issue by alquerci** [LExpress/symfony1#196]
This bug provide a different behaviour than Doctrine1 do:

https://github.com/LExpress/doctrine1/blob/v1.3.6/lib/Doctrine/Import/Schema.php#L330

How to reproduce?
------------------------

```yml
connection: doctrine
options:
  charset: utf8

Foo:
  options:
    symfony:
      form: false
```

Expected
-----------

```yml
Foo:
  connection: doctrine
  options:
    charset: utf8
    symfony:
      form: false
```

Actual
--------

```yml
Foo:
  connection: doctrine
  options:
    symfony:
      form: false
```

Track for fix
---------------

Using a deep merge instead of the simple `array_merge()` function can be a solution.

- https://github.com/LExpress/symfony1/blob/v1.5.11/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBaseTask.class.php#L151
- https://github.com/LExpress/symfony1/blob/v1.5.11/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBaseTask.class.php#L182
